# Generated by Django 6.1.1 on 2026-09-11 17:49

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='recipient_name',
            field=models.CharField(default='تست', max_length=100, verbose_name='نام گیرنده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(editable=False, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تأیید شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='postal_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='کد پستی باید دقیقاً ده رقم باشد.', regex='^\\d{10}$')], verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='recipient_phone',
            field=models.CharField(max_length=11, validators=[apps.accounts.models.mobile_validate], verbose_name='شماره تماس گیرنده'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد'),
        ),
    ]
