# Generated by Django 6.1.1 on 2026-09-11 18:04

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_create_order_number_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(db_default=django.db.models.expressions.RawSQL("nextval('orders_order_number_seq')", []), editable=False, unique=True, verbose_name='شماره سفارش'),
        ),
    ]
