# Generated by Django 6.1.1 on 2026-09-24 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_discount_eligible_users'),
        ('orders', '0005_order_expires_at_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['expires_at'], name='orders_pending_expires_idx'),
        ),
    ]
