# Generated by Django 6.1.1 on 2026-09-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_number', '-created_at'], name='accounts_ot_phone_n_5c3b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_number', 'is_used'], name='accounts_ot_phone_n_3bd7df_idx'),
        ),
    ]
