# Generated by Django 6.1.1 on 2026-09-29 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='guest_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='شناسه مهمان'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_token__isnull', True), ('user__isnull', False)), models.Q(('guest_token__isnull', False), ('user__isnull', True)), _connector='OR'), name='cart_exactly_one_owner'),
        ),
    ]
