# Generated by Django 6.1.1 on 2026-09-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_date'),
        ('payments', '0002_payment_gateway_response_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه تراکنش'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('order',), name='unique_pending_payment_per_order'),
        ),
    ]
