# Generated by Django 6.1.1 on 2026-09-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_date'),
        ('payments', '0003_alter_payment_tracking_code_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('order',), name='unique_success_payment_per_order'),
        ),
    ]
