# Generated by Django 6.1.1 on 2026-09-10 18:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مقدار تخفیف')),
                ('target_type', models.CharField(choices=[('order', 'کل سفارش'), ('product', 'محصولات'), ('category', 'دسته بندی'), ('brand', 'برند')], max_length=20, verbose_name='محدوده تخفیف')),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='حداقل مبلغ کل سبد')),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف استفاده کل')),
                ('per_user_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف استفاده هر کاربر')),
                ('starts_at', models.DateTimeField(verbose_name='تاریخ و زمان شروع')),
                ('ends_at', models.DateTimeField(verbose_name='تاریخ و زمان پایان')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('brands', models.ManyToManyField(blank=True, related_name='discounts', to='catalog.brand', verbose_name='برندها')),
                ('categories', models.ManyToManyField(blank=True, related_name='discounts', to='catalog.category', verbose_name='دسته\u200cبندی\u200cها')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='catalog.product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
                'ordering': ('-created_at',),
            },
        ),
    ]
