# Generated by Django 6.1.1 on 2026-09-11 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان استفاده')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='discounts.discount', verbose_name='تخفیف')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usages', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از کد تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای کد تخفیف',
                'constraints': [models.UniqueConstraint(fields=('discount', 'order'), name='unique_discount_per_order')],
            },
        ),
    ]
