# Generated by Django 6.1.1 on 2026-09-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_discount_eligible_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('-priority', '-created_at'), 'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف\u200cها'},
        ),
        migrations.AddField(
            model_name='discount',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='اگر چند تخفیف هم\u200cزمان معتبر باشند، عدد بزرگ\u200cتر برنده است. تخفیف\u200cها با هم جمع نمی\u200cشوند.', verbose_name='اولویت'),
        ),
    ]
