# Generated by Django 6.1.1 on 2026-09-30 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_name'),
        ('discounts', '0005_alter_discount_options_discount_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان تخفیف'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='discount_active_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='discount_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='discount_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percentage'), _negated=True), ('value__lte', 100), _connector='OR'), name='discount_percentage_max_100'),
        ),
    ]
