# Generated by Django 6.1.1 on 2026-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_discount_title_discount_discount_active_period_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='minimum_order_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='مبلغ را به ریال وارد کنید. مثال: 1000000', max_digits=12, null=True, verbose_name='حداقل مبلغ کل سبد'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=0, help_text='برای تخفیف درصدی فقط عدد وارد کنید (مثال: 20)؛ برای تخفیف مبلغ ثابت، مبلغ را به ریال وارد کنید (مثال: 500000).', max_digits=12, verbose_name='مقدار تخفیف'),
        ),
    ]
