# Generated by Django 6.1.1 on 2026-09-12 18:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('method', models.CharField(choices=[('post', 'پست'), ('courier', 'پیک'), ('other', 'سایر')], max_length=20, verbose_name='روش ارسال')),
                ('carrier', models.CharField(max_length=100, verbose_name='شرکت/سرویس حمل')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری')),
                ('shipping_cost', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='هزینه ارسال')),
                ('status', models.CharField(choices=[('pending', 'در انتظار ارسال'), ('processing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت ارسال')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'مرسوله',
                'verbose_name_plural': 'مرسوله\u200cها',
                'ordering': ('-created_at',),
            },
        ),
    ]
