# Generated by Django 6.1.1 on 2026-09-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدل'),
        ),
    ]
