# Generated by Django 6.1.1 on 2026-09-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='متن جایگزین تصویر')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='تصویر دسکتاپ')),
                ('mobile_image', models.ImageField(blank=True, upload_to='banners/mobile/%Y/%m/', verbose_name='تصویر موبایل')),
                ('link', models.CharField(blank=True, help_text='آدرس کامل یا مسیر داخلی مثل /products/oil', max_length=500, verbose_name='لینک')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='باز شدن در تب جدید')),
                ('position', models.CharField(choices=[('home_slider', 'اسلایدر صفحه اصلی')], db_index=True, default='home_slider', max_length=32, verbose_name='جایگاه')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع نمایش')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['position', 'sort_order', '-id'],
                'indexes': [models.Index(fields=['position', 'is_active', 'sort_order'], name='banners_ban_positio_c28d54_idx')],
            },
        ),
    ]
